# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Pipeline iteration: {ITERATION}
# This notebook is auto-generated by `scripts/build_notebook.py` from
# `pipeline/notebook_template.py` + the iteration's `config.yaml`.

# %%
import os, sys, shutil, json, pathlib
REPO = pathlib.Path("/kaggle/working/repo")

# The kernel push sends the whole `pipeline/` directory. On Kaggle that lives
# alongside the notebook in /kaggle/working. We also need the iteration config,
# which build_notebook.py copies next to the notebook.
sys.path.insert(0, "/kaggle/working")

# %%
from pipeline.src.train import run

COMP_SLUG = "{COMP_SLUG}"
ITERATION = "{ITERATION}"

metrics = run(
    config_path=f"/kaggle/working/iteration_config.yaml",
    input_dir=f"/kaggle/input/{COMP_SLUG}",
    output_dir="/kaggle/working",
)
print(json.dumps(metrics, indent=2))
